DATA.erfindungen = [
  {event:"Das Rad erfunden",year:-3500,icon:"☸️",info:"Um 3500 v. Chr. wurde das Rad in Mesopotamien erfunden."},
  {event:"Papyrus erfunden",year:-3000,icon:"📃",info:"Um 3000 v. Chr. begannen die Ägypter Papyrus herzustellen."},
  {event:"Eisenzeit beginnt",year:-1200,icon:"⚒️",info:"Um 1200 v. Chr. begann die Eisenzeit."},
  {event:"Magnetkompass erfunden",year:200,icon:"🧭",info:"Um 200 n. Chr. nutzten Chinesen den Magnetkompass."},
  {event:"Schwarzpulver entdeckt",year:850,icon:"💥",info:"Um 850 entdeckten chinesische Alchemisten das Schwarzpulver."},
  {event:"Buchdruck erfunden (Gutenberg)",year:1450,icon:"📖",info:"Um 1450 erfand Gutenberg den Buchdruck."},
  {event:"Teleskop verbessert (Galilei)",year:1609,icon:"🔭",info:"1609 revolutionierte Galilei die Astronomie."},
  {event:"Dampfmaschine verbessert (Watt)",year:1769,icon:"♨️",info:"1769 verbesserte Watt die Dampfmaschine."},
  {event:"Erste Batterie (Volta)",year:1800,icon:"🔋",info:"1800 baute Volta die erste Batterie."},
  {event:"Erste Eisenbahn",year:1825,icon:"🚂",info:"1825 fuhr die erste öffentliche Eisenbahn."},
  {event:"Fotografie erfunden (Daguerre)",year:1839,icon:"📷",info:"1839 präsentierte Daguerre die Daguerreotypie."},
  {event:"Telefon erfunden (Bell)",year:1876,icon:"📞",info:"1876 patentierte Bell das Telefon."},
  {event:"Glühbirne erfunden (Edison)",year:1879,icon:"💡",info:"1879 entwickelte Edison die Glühbirne."},
  {event:"Automobil erfunden (Benz)",year:1886,icon:"🚗",info:"1886 patentierte Benz das erste Automobil."},
  {event:"Röntgenstrahlen entdeckt",year:1895,icon:"☢️",info:"1895 entdeckte Röntgen die Strahlen."},
  {event:"Erster Motorflug (Gebr. Wright)",year:1903,icon:"✈️",info:"1903 hoben die Brüder Wright ab."},
  {event:"Relativitätstheorie (Einstein)",year:1905,icon:"⚡",info:"1905 veröffentlichte Einstein E=mc²."},
  {event:"Penicillin entdeckt (Fleming)",year:1928,icon:"💊",info:"1928 entdeckte Fleming das Penicillin."},
  {event:"Erster Computer (Z3)",year:1941,icon:"🖥️",info:"1941 baute Zuse den ersten Computer."},
  {event:"Transistor wird erfunden",year:1947,icon:"🔌",info:"1947 wurde der Transistor erfunden."},
  {event:"DNA entschlüsselt (Watson & Crick)",year:1953,icon:"🧬",info:"1953 entschlüsselten Watson und Crick die DNA."},
  {event:"Erster Satellit (Sputnik)",year:1957,icon:"🛰️",info:"1957 startete der erste Satellit ins All."},
  {event:"Geburt des Internets (ARPANET)",year:1969,icon:"🌐",info:"1969 vernetzte ARPANET erstmals Computer."},
  {event:"World Wide Web erfunden (Berners-Lee)",year:1991,icon:"🕸️",info:"1991 machte Berners-Lee das WWW öffentlich."},
  {event:"Erstes iPhone",year:2007,icon:"📱",info:"2007 stellte Jobs das iPhone vor."},
  {event:"ChatGPT erscheint",year:2022,icon:"🤖",info:"2022 machte ChatGPT KI massentauglich."},
];
