DATA.film = [
  {event:"Lumières: Erste öffentliche Filmvorführung",year:1895,icon:"🎞️",info:"1895 zeigten die Brüder Lumière den ersten öffentlichen Film."},
  {event:"Erster Langfilm: The Kelly Gang",year:1906,icon:"🎬",info:"1906 entstand The Story of the Kelly Gang – der erste Langfilm."},
  {event:"Chaplin dreht The Kid",year:1921,icon:"🎩",info:"1921 erschien Chaplins erster Langfilm The Kid."},
  {event:"The Jazz Singer: Erster Tonfilm",year:1927,icon:"🔊",info:"1927 erschien The Jazz Singer – der erste Tonfilm."},
  {event:"Disneys Schneewittchen erscheint",year:1937,icon:"🍎",info:"1937 erschien Schneewittchen – der erste abendfüllende Zeichentrickfilm."},
  {event:"Citizen Kane kommt ins Kino",year:1941,icon:"🎥",info:"1941 erschien Citizen Kane – oft als bester Film aller Zeiten genannt."},
  {event:"Dr. No: Erster James-Bond-Film",year:1962,icon:"🔫",info:"1962 erschien Dr. No mit Sean Connery als 007."},
  {event:"Coppola dreht Der Pate",year:1972,icon:"🌹",info:"1972 erschien Der Pate – ein Meilenstein des Gangsterfilms."},
  {event:"Lucas dreht Star Wars",year:1977,icon:"⭐",info:"1977 revolutionierte Star Wars das Kino."},
  {event:"Spielberg dreht Jurassic Park",year:1993,icon:"🦖",info:"1993 setzte Jurassic Park neue Maßstäbe bei visuellen Effekten."},
  {event:"Titanic wird zum Kassenschlager",year:1997,icon:"🚢",info:"1997 wurde Titanic zum erfolgreichsten Film aller Zeiten."},
  {event:"Jackson dreht Herr der Ringe",year:2001,icon:"💍",info:"2001 startete Peter Jacksons Herr-der-Ringe-Trilogie."},
  {event:"Avatar revolutioniert 3D-Kino",year:2009,icon:"🌍",info:"2009 revolutionierte Avatar die 3D-Technik im Kino."},
  {event:"Netflix produziert ersten Originalfilm",year:2015,icon:"📺",info:"2015 startete Netflix mit eigenen Filmen – das Streaming-Zeitalter."},
];
